se_path: "F:/Steam/steamapps/common/SpaceEngineers/Content"
mods_path: "F:/Steam/steamapps/workshop/content/244850"
logger:
  handlers:
    stream:
      level: INFO
      bubble: false
#    timed_rotating_file:
#      level: INFO
#      bubble: true
#      date_format: "%Y-%m-%d_%H:%M:%S"